# Generated by Django 3.1.4 on 2021-01-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20210111_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='Accounts.Tag'),
        ),
    ]
