# Generated by Django 3.1.4 on 2021-01-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
